services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
    volumes:
      - .:/app

  ngrok:
    image: ngrok/ngrok:latest
    platform: linux/arm64
    ports:
      - "4040:4040"
    env_file:
      - .env
    command: http web:8080
    depends_on:
      - web
